### ISSUE TITLE
A user can view skate spots.

### ISSUE THREAD

**Issue by anthonyrodarte** [anthonyrodarte/fifty-fifty#1]
**Motivation**

Let's get started by displaying some spots on the phone. These spots will be pulled from the Yelp API and will be displayed as cards to the user.

**Tasks**

- [x] Create Logo
- [x] Build a card component
- [x] Acquire Yelp API access key
- [x] Pull Skate Parks from Yelp API
- [x] Store Skate Parks in Database
- [x] Use Skate Park Data to fill cards

**Wireframe**

![screen shot 2018-11-14 at 7 01 42 pm](https://user-images.githubusercontent.com/22861295/48527414-f07b5b80-e83f-11e8-82fd-9674238ec40f.png)

**Comment by anthonyrodarte** [comment]
![07d3786ba8f9c6a06dc66a39f249b956](https://user-images.githubusercontent.com/22861295/52320179-bb842e00-2982-11e9-8102-2fafdcfffbde.gif)
