### ISSUE TITLE
A user can visit the spot page

### ISSUE THREAD

**Issue by anthonyrodarte** [anthonyrodarte/fifty-fifty#15]
**Motivation**

We want to create a dedicated page for the spot where the user can view all the media that will be posted to the spot.

**Tasks**

- [x] Create wireframe
- [ ] Create static front end component
- [ ] Create route for querying single skatepark from DB
- [ ] Synchronize front end with route data

**Wireframe**

![Screen Shot 2019-05-16 at 6 30 24 PM](https://user-images.githubusercontent.com/22861295/57897249-cca5cc00-7808-11e9-99fa-0eadd3f661f9.png)
